
name: 📦 DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      # - name: Debug secrets (sanitized)
      #   run: echo "Docker username is ${{ secrets.DOCKER_USERNAME }}"
        
      # - name: Checkout code
      #   uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          
